### ISSUE TITLE
Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView

### ISSUE THREAD

**Issue by a8453770** [lzyzsd/JsBridge#114]
12-22 11:06:24.668 15010-15010/com.emuzi.wallet E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.emuzi.wallet/com.emuzi.wallet.module.webview.WebActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                      Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView
                                                                      Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                         at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:446)
                                                                         at android.app.Activity.setContentView(Activity.java:2544)
                                                                         at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276)
                                                                         at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
                                                                         at com.emuzi.wallet.module.webview.WebActivity.setRootView(WebActivity.java:35)
                                                                         at com.emuzi.wallet.module.BaseActivity.onCreate(BaseActivity.java:78)
                                                                         at android.app.Activity.performCreate(Activity.java:6942)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                      Caused by: java.lang.IllegalArgumentException: Unsupported ABI: null
                                                                         at dalvik.system.VMRuntime.getInstructionSet(VMRuntime.java:370)
                                                                         at dalvik.system.VMRuntime.is64BitAbi(VMRuntime.java:383)
                                                                         at android.webkit.WebViewFactory.getWebViewNativeLibraryPaths(WebViewFactory.java:505)
                                                                         at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:630)
                                                                         at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:344)
                                                                         at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
                                                                         at android.webkit.WebView.getFactory(WebView.java:2325)
                                                                         at android.webkit.WebView.ensureProviderCreated(WebView.java:2320)
12-22 11:06:24.668 15010-15010/com.emuzi.wallet E/UncaughtException:     at android.webkit.WebView.setOverScrollMode(WebView.java:2379)
                                                                         at android.view.View.<init>(View.java:4318)
                                                                         at android.view.View.<init>(View.java:4460)
                                                                         at android.view.ViewGroup.<init>(ViewGroup.java:579)
                                                                         at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
                                                                         at android.webkit.WebView.<init>(WebView.java:627)
                                                                         at android.webkit.WebView.<init>(WebView.java:572)
                                                                         at android.webkit.WebView.<init>(WebView.java:555)
                                                                         at android.webkit.WebView.<init>(WebView.java:542)
                                                                         at com.github.lzyzsd.jsbridge.BridgeWebView.<init>(BridgeWebView.java:44)
                                                                         	... 30 more

**Comment by a8453770** [comment]
在很多手机上都能正常运行,唯独三星note5上面出错

**Comment by a8453770** [comment]
@lzyzsd SM-N920I 系统7.0 api24  运行demo 也直接奔溃

**Comment by dazeGitHub** [comment]
解决了吗，

**Comment by zhaoyongjiang** [comment]
解决了吗？我这在oppo机上必崩。。求教啊。项目急上线

**Comment by zhaoyongjiang** [comment]
https://www.v2ex.com/t/493325

**Comment by Jay-Droid** [comment]
Android 5.1.1 上好像是必现 Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView

**Comment by hxkdidi** [comment]
pixel2 10.0系统偶现

**Comment by hxkdidi** [comment]
采用如下方式：

mWebView = new BridgeWebView(activity);
ll_layout.addView(mWebView);

**Comment by OOOOOldZhu** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.junxin.zeropay/com.junxin.zeropay.activity.main.WebActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003 at com.junxin.zeropay.activity.base.BaseActivity.onCreate(BaseActivity.java:6)

设备机型:
vivo
是否Root:
否
地域:
中国河南省开封市
机型版本:
vivo X6S A
设备电量:
61.0
电池温度:
257.0
渠道信息:
junxin
磁盘可用占比:
45.48
内存可用占比:
4.57
现在是2020.12.14，看来这个问题是没有解决办法了？

**Comment by RDSunhy** [comment]
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.junxin.zeropay/com.junxin.zeropay.activity.main.WebActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003 at com.junxin.zeropay.activity.base.BaseActivity.onCreate(BaseActivity.java:6)
> 
> 设备机型:
> vivo
> 是否Root:
> 否
> 地域:
> 中国河南省开封市
> 机型版本:
> vivo X6S A
> 设备电量:
> 61.0
> 电池温度:
> 257.0
> 渠道信息:
> junxin
> 磁盘可用占比:
> 45.48
> 内存可用占比:
> 4.57
> 现在是2020.12.14，看来这个问题是没有解决办法了？

你检查下你的androidx.appcompat:appcompat是什么版本的 我刚刚解决了这个问题。在低端机上会经常报错这个。把版本改为1.2.0就ok了；我也觉得很不可思议，但是我就是这么解决的，你可以试试；

**Comment by beiliubei** [comment]
https://gist.github.com/tw-Frey/2eb7b7d983027aae9b9b809052e4e2b8   webview androidx.appcompat:appcompat 兼容bug
