### ISSUE TITLE
Android 8.0下运行崩溃

### ISSUE THREAD

**Issue by erichyx** [lzyzsd/JsBridge#153]
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
                      at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:438)
                      at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
                      at android.webkit.WebView.getFactory(WebView.java:2467)
                      at android.webkit.WebView.ensureProviderCreated(WebView.java:2462)
                      at android.webkit.WebView.setOverScrollMode(WebView.java:2527)
                      at android.view.View.<init>(View.java:4536)
                      at android.view.View.<init>(View.java:4668)
                      at android.view.ViewGroup.<init>(ViewGroup.java:597)
                      at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
                      at android.webkit.WebView.<init>(WebView.java:636)
                      at android.webkit.WebView.<init>(WebView.java:581)
                      at android.webkit.WebView.<init>(WebView.java:564)
                      at android.webkit.WebView.<init>(WebView.java:551)
                      at com.github.lzyzsd.jsbridge.BridgeWebView.<init>(BridgeWebView.java:40)

**Comment by ButterRhopa** [comment]
你这个是你使用的手机的问题，没有安装webview
