### ISSUE TITLE
JS调用Android端没有的方法会抛空指针异常

### ISSUE THREAD

**Issue by imliujun** [lzyzsd/JsBridge#19]
UncaughtException in Thread main
                                                       java.lang.NullPointerException
                                                           at com.github.lzyzsd.jsbridge.BridgeWebView$1.onCallBack(BridgeWebView.java:228)
                                                           at com.github.lzyzsd.jsbridge.BridgeWebView.handlerReturnData(BridgeWebView.java:75)
                                                           at com.github.lzyzsd.jsbridge.BridgeWebView.access$000(BridgeWebView.java:23)
                                                           at com.github.lzyzsd.jsbridge.BridgeWebView$BridgeWebViewClient.shouldOverrideUrlLoading(BridgeWebView.java:91)
                                                           at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:354)
                                                           at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:488)
                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                           at android.os.Looper.loop(Looper.java:176)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:525)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by imliujun** [comment]
BridgeWebView.java 第228行加一个非空判断就可以了。

**Comment by imliujun** [comment]
已经提交了Pull request
