### ISSUE TITLE
Android Studio Dolphin | 2021.3.1 Patch 1预览问题

### ISSUE THREAD

**Issue by jzlhll** [lzyzsd/JsBridge#262]
新版无法正常，预览，会提示预览报错。
java.lang.NoSuchMethodError: 'android.webkit.WebSettings com.github.lzyzsd.jsbridge.BridgeWebView.getSettings()'
	at com.github.lzyzsd.jsbridge.BridgeWebView.init(BridgeWebView.java:71)
	at com.github.lzyzsd.jsbridge.BridgeWebView.<init>(BridgeWebView.java:45)

The following classes could not be instantiated:
- com.typhur.module.base.typhur.view.TyphurWebView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  
 If this is an unexpected error you can also try to build the project, then manually refresh the layout.

是不是应该把init()函数添加一下View.isInEditMode()控制下？

**Comment by keluokeda** [comment]
同样有这个问题
