### ISSUE TITLE
混淆规则

### ISSUE THREAD

**Issue by pengbs** [lzyzsd/JsBridge#54]
请问，这个库需要混淆吗？混淆规则是什么样的呢？

**Comment by lilipu1** [comment]
我也想问这个问题,你找到解决方案了吗?

**Comment by scsfwgy** [comment]
08-03 21:47:58.575 11344-11344/com.tophold.xcfd W/System.err: org.b.b: JSONObject["data"] not a string.
        at org.b.c.h(JSONObject.java:639)
        at com.github.lzyzsd.jsbridge.f.f(Message.java:102)
        at com.github.lzyzsd.jsbridge.BridgeWebView$1.a(BridgeWebView.java:147)
        at com.github.lzyzsd.jsbridge.BridgeWebView.a(BridgeWebView.java:87)
        at com.github.lzyzsd.jsbridge.c.shouldOverrideUrlLoading(BridgeWebViewClient.java:29)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:343)
        at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:261)
        at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5418)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by scsfwgy** [comment]
#143
